name: myhealthhub-dev-cicd-web-main

on:
  push:
    branches:
      - main
    paths:
      - "src/myhealthhub.web/**"
      
  pull_request:
    branches:
      - main
    paths:
      - "src/myhealthhub.web/**"
      
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: .\src\myhealthhub.web
      
    - name: Setup NuGet.exe for restore
      uses: NuGet/setup-nuget@v1.0.5
    - run: nuget restore .\src\myhealthhub.web\myhealthhub.web.csproj
      
    #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'src/myhealthhub.web/appsettings.json'
      env:
        AzureAd.Instance: ${{ secrets.AZUREAD_INSTANCE }}
        AzureAd.Domain: ${{ secrets.AZUREAD_DOMAIN }}
        AzureAd.TenantId: ${{ secrets.AZUREAD_TENANTID }}
        AzureAd.ClientId: ${{ secrets.AZUREAD_CLIENTID }}
        AzureAd.ClientSecret: ${{ secrets.CLIENTSECRET }}
        AzureAd.CallbackPath: ${{ secrets.CALLBACKPATH }}
        AzureAd.AllowWebApiToBeAuthorizedByACL: ${{ secrets.ALLOWWEBAPITOBRAUTHORIZEDBYACL }}
        AccessToken.TokenResource: ${{ secrets.TOKENRESOURCE }}
        AccessToken.GrantType: ${{ secrets.GRANTTYPE }}
        AccessToken.Resource: ${{ secrets.RESOURCE }}
        MyHealthHubApi.BaseUrl: ${{ secrets.BASEURL }}
        MyHealthHubApi.PatientResource: ${{ secrets.PATIENTRESOURCE }}
        MyHealthHubApi.PhysicianResource: ${{ secrets.PHYSICIANRESOURCE }}
        MyHealthHubApi.FormLabelResource: ${{ secrets.FORMLABEL }}
        MyHealthHubApi.StudyResource: ${{ secrets.STUDYRESOURCE }}
        MyHealthHubApi.VisitResource: ${{ secrets.VISITRESOURCE }}
        MyHealthHubApi.TrialFormResource: ${{ secrets.TRIALFORMRESOURCE }}
        MyHealthHubApi.TrialCompletionFormResource: ${{ secrets.TRIALCOMPLETIONFORMRESOURCE }}
        MyHealthHubApi.BaselineFormResource: ${{ secrets.BASELINEFORMRESOURCE }}
        MyHealthHubApi.FormLabelPerVisitResource: ${{ secrets.FORMLABELPERVISITRESOURCE }}
        MyHealthHubApi.StudyPerPhysicianResource: ${{ secrets.STUDYPERPHYSICIANRESOURCE }}
        MyHealthHubApi.VisitPerStudyResource: ${{ secrets.VISITPERSTUDYRESOURCE }}
        MyHealthHubApi.VisitPerPatientResource: ${{ secrets.VISITPERPATIENTRESOURCE }}
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: .\src\myhealthhub.web
      
    - name: Publish
      run: dotnet publish -c Release -o myhealthhub-dev-web
      working-directory: .\src\myhealthhub.web
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV_WEB }}
    
    - name: Selecting the target Subscription
      run: az account set -s "${{ secrets.SUBSCRIPTION_ID }}"
      
    - name: Updating Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: myhealthhubapi-dev-webapp-web
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: .\src\myhealthhub.web\myhealthhub-dev-web
